-- MySQL Script generated by MySQL Workbench
-- Thứ sáu, 15 Tháng 3 Năm 2019 15:38:04 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema voting_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voting_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voting_project` DEFAULT CHARACTER SET utf8 ;
USE `voting_project` ;

-- -----------------------------------------------------
-- Table `voting_project`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_project`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `voting_project`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_project`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `vote_ability` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `voting_project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_project`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_role` INT NOT NULL,
  `id_team` INT NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT NULL,
  `other` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_1_idx` (`id_team` ASC),
  INDEX `fk_user_2_idx` (`id_role` ASC),
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`id_team`)
    REFERENCES `voting_project`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_2`
    FOREIGN KEY (`id_role`)
    REFERENCES `voting_project`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `voting_project`.`awardDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_project`.`awardDetail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `date_start` DATETIME NOT NULL,
  `date_end` DATETIME NOT NULL,
  `price` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `voting_project`.`votingBreakdown`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_project`.`votingBreakdown` (
  `year` INT NOT NULL,
  `rank` INT NOT NULL,
  `id_nominee` INT NOT NULL,
  `first_votes` INT NOT NULL,
  `second_votes` INT NOT NULL,
  `third_votes` INT NOT NULL,
  `percent` FLOAT NOT NULL,
  `total_points` INT NOT NULL,
  INDEX `fk_votingBreakdown_1_idx` (`id_nominee` ASC),
  PRIMARY KEY (`year`, `rank`),
  CONSTRAINT `fk_votingBreakdown_1`
    FOREIGN KEY (`id_nominee`)
    REFERENCES `voting_project`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `voting_project`.`finalResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_project`.`finalResult` (
  `year` INT NOT NULL,
  `id_winner` INT NOT NULL,
  `id_award` INT NOT NULL,
  PRIMARY KEY (`year`),
  INDEX `fk_finalResult_1_idx` (`id_winner` ASC),
  INDEX `fk_finalResult_2_idx` (`id_award` ASC),
  CONSTRAINT `fk_finalResult_1`
    FOREIGN KEY (`id_winner`)
    REFERENCES `voting_project`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_finalResult_2`
    FOREIGN KEY (`id_award`)
    REFERENCES `voting_project`.`awardDetail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_finalResult_3`
    FOREIGN KEY (`year`)
    REFERENCES `voting_project`.`votingBreakdown` (`year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `voting_project`.`awardRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_project`.`awardRole` (
  `id_award` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_award`),
  INDEX `fk_awardRole_2_idx` (`id_role` ASC),
  CONSTRAINT `fk_awardRole_1`
    FOREIGN KEY (`id_award`)
    REFERENCES `voting_project`.`awardDetail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_awardRole_2`
    FOREIGN KEY (`id_role`)
    REFERENCES `voting_project`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
